### ISSUE TITLE
Move to catch2 v3?

### ISSUE THREAD

**Issue by Yurlungur** [lanl/singularity-eos#309]
At some point it may be worth modernizing our test infrastructure by moving from v2 of catch2 to v3. v3 is not header-only, it's more a proper static library, which should speed up compilation/linking times, as the entire catch library doesn't need to be built/linked per translation unit.

My question for you all is: what are the impediments to doing so from the perspective of our tooling?
- @mauneyc-LANL you have a comment in the singularity-eos build that v2.13.7 is the version of catch that works with clang/newer compilers. Is this a problem for updating to newer catch?
- Similarly, do we need update `Spiner` and `ports-of-call` to newer catch if we want `singularity-eos` updated?
- Finally, for spack, is it enough to change the target in the spackage? Or do we need to install catch v3 on the CI shared spack? (Question for @ktsai7 or @rbberger )

**Comment by ktsai7** [comment]
@Yurlungur if you change the dependency to `catch2@3.x` in the spackage, it will get pulled in and installed during CI, so it shouldn't stop your development

The CI will be slightly slower since it has to build the `catch2@3.x` inflight until the next regular deployment cycle that pulls in the updated newer spackage after the spackaage has been merged in. If this slowed down is too much, then let me know and I can trigger a manual deployment update to pull the package in.

**Comment by dholladay00** [comment]
Isn't this now completed @Yurlungur ?

**Comment by Yurlungur** [comment]
No this is the one thing I didn't get to when messing with the tests.

**Comment by dholladay00** [comment]
This is now done correct?

**Comment by Yurlungur** [comment]
Yes.
