### ISSUE TITLE
How to best handle switch from header-only to compiled with/without fortran?

### ISSUE THREAD

**Issue by Yurlungur** [lanl/singularity-eos#323]
In my recent `EOSBuilder` cleanup (see #311 ), I was able to eliminate all compiled parts of `singularity-eos` when it is built as a C++ library, making it entirely header only. Unfortunately, this presents a problem with cmake, as we sometimes build `singularity-eos` as header-only and sometimes with compiled parts. When we build as header-only, we must mark `singularity-eos` as `INTERFACE` in `CMake`. We must also slurp in all dependencies with the `INTERFACE` flag. When we compile, in contrast, we cannot use the `INTERFACE` flag. This creates a lot of branching in the build system. 

My current solution (in #311 anyway) is to just create an empty, dummy file to compile, even when the code is header-only. But of course this isn't ideal. What is the right solution here, @rbberger @mauneyc-LANL ?

**Comment by rbberger** [comment]
I agree with @cmauney that splitting this into two target sets and making it available as COMPONENTS seems to be the cleanest solution.

**Comment by rbberger** [comment]
@Yurlungur there is another point here for splitting the CMake into multiple COMPONENTS. Fortran bindings don't need to check for dependencies like `ports-of-call` and `mpark-variant` anymore, since those are already compiled into the bindings.

Right now, `find_package(singularity-eos)` forces `find_package(ports-of-call)` and `find_package(mpark-variant)`. See https://github.com/lanl/singularity-eos/blob/main/config/singularity-eosConfig.cmake.in#L41-L43

Instead, what we actually would want is something like this from a host-code:
```cmake
find_package(singularity-eos COMPONENTS Fortran)
# could provide something like singularity-eos::singularity-eos_Fortran
# but should not check for header dependencies anymore
```

This would clean up host-code integration, by avoiding the requirement of `ports-of-call` and `mpark-variant`  to be present in the build environment, even though nothing in a Fortran build system will consume it.
