### ISSUE TITLE
Add EOSPAC Vector Calls

### ISSUE THREAD

**Issue by jhp-lanl** [lanl/singularity-eos#92]
Add vector calls specific to EOSPAC

Related issues:
- How do we make modifiers work with EOSPAC performantly?

**Comment by rbberger** [comment]
Been thinking about this. At least for a subset of modifiers, what they actually are doing is applying factors for X, Y, and/or F values, similar to what we are doing for unit conversion in EOSPAC. So one way would be to allow modifiers to set some state for each of those factors and then call the base type vector functions with unmodified data. In the EOSPAC case setting the state would then define/modify EOSPAC options. It would also mean that instead of overriding the existing EOSPAC factors during the vector calls, we would apply our factors on top of them and reset them to their previous value after the vector call. But it also means that in some cases we can no longer do XY_PASSTHROUGH. Another issue, that so far hasn't been considered is thread-safety of vector calls.

For other modifiers (e.g. shift) we might have use extra scratch space to first transform the input data.

**Comment by jhp-lanl** [comment]
I assume this would mean adding new functions to the modifiers that are disabled when the type contained in the `Variant` class isn't EOSPAC?

I think you're right about how to tackle this for scaling ratios, and I think a scratch array is inevitable for shifts.

Thinking about ramps: The usual way to compute a ramp is to both call the EOS for the pressure at a given density and calculate the bilinear ramp pressure while only taking the maximum of the two. The current vector interface simply loops over the scalar EOS call and maxing, while an EOSPAC-friendly verison would have to call the EOS vector interface and then loop over states to do the maxing. I suspect the latter incurs a performance cost for executing two loops instead of one (especially when those are host loops launching device kernels), so we may want to disable the EOSPAC-friendly ramp for all other EOS.

**Comment by jhp-lanl** [comment]
> The way I have it now, doesn't mean extra functions but an additional optional parameter that is default constructed. It's invisible to the Variant, but part of EOSBase. Modifiers and EOSPAC make use of this additional parameter, modify it and pass it down the chain, until it reaches the vector call, where the factors are then used.
> 
> Basically that means in the vector calls in things like ScaledEOS don't actually do anything other than modify that object, and pass it down.

That sounds like a good idea!

**Comment by rbberger** [comment]
So far I have ShiftedEOS, ScaledEOS.

UnitSystem and RelativisticEOS should be easy now, however EOSPAC isn't a valid variant that uses those two. Should I skip them and instead forcus on BilinearRampEOS?

**Comment by Yurlungur** [comment]
Yeah skip them for now. I think `RelativisticEOS` is maybe something we should consider removing. `UnitSystem` maybe requires a longer conversation, as I think we *probably* want it. But lower priority.

**Comment by jhp-lanl** [comment]
I think @rbberger took care of this. Closing the issue
